title: <p align = "center"> Matheus da Silva </p> 


logo: "/images/MVIMG_20220129_142200-01-modified.png?raw=true"

description: 
  <p align = "center">
  <a href = "pdf/curriculo_git.pdf">Resumo</a> | 
  <a href = "https://www.linkedin.com/in/matheus-oliveira-064242129/">LinkedIn</a> |
  <a href = "https://github.com/math-prog">GitHub</a> 
  </p>
  
  <p align = "justify">
  Sou graduado em Engenheria Mecânica pela Universidade Evangélica de Goiás e certificado como Cientista de Dados pela Data Science Academy.
  <br><br>
  Atualmente construo modelos preditivo com intuitos de trazer resultados financeiros relevantes para empresa, melhorando a experiência e permanência dos usuários, tudo isso através dos dados.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
